use oficina_dio;
Drop table if exists Ordem_Servico;

create table Pecas (
	idPecas INT primary key,
	Auto_parts VARCHAR(50),
	Brand VARCHAR(50),
	Model VARCHAR(50),
	Price DECIMAL(6,2)
);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (1, 'Piston', 'Dodge', 'd8H-29', 414.98);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (2, 'Alternator', 'Pontiac', '3OF-21', 176.72);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (3, 'Spark Plug', 'Ford', '4Sm-80', 1755.31);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (4, 'Clutch', 'Acura', 'YNI-01', 1219.88);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (5, 'Clutch', 'BMW', 'meE-36', 1397.02);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (6, 'Alternator', 'Dodge', 'qjI-98', 2350.67);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (7, 'Fuel Injector', 'Chevrolet', 'RRi-58', 498.17);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (8, 'A/C Compressor', 'Nissan', 'pyc-56', 1195.85);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (9, 'Shock Absorbers', 'Oldsmobile', 'xJu-99', 1607.76);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (10, 'Clutch', 'Pontiac', 'Jhg-25', 1907.29);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (11, 'Radiator', 'Chevrolet', '3Xv-09', 148.01);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (12, 'Radiator', 'Lincoln', 'psw-94', 260.62);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (13, 'Alternator', 'Audi', 'tek-66', 1281.2);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (14, 'Muffler', 'Volkswagen', 'C3c-97', 415.32);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (15, 'Alternator', 'Cadillac', 'bCr-67', 393.82);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (16, 'Muffler', 'Suzuki', '0KR-88', 522.03);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (17, 'Radiator', 'Pontiac', 'q16-79', 1517.68);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (18, 'Shock Absorbers', 'Mitsubishi', 'jCx-01', 1825.56);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (19, 'Catalytic Converter', 'Mitsubishi', 'KYc-49', 190.43);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (20, 'Engine Fan', 'Ford', '6N8-97', 1619.76);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (21, 'Transmission', 'Ford', 'ihk-56', 2695.82);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (22, 'Alternator', 'Isuzu', 'uE8-78', 649.81);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (23, 'Air Filter', 'Mercury', '1kw-90', 323.82);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (24, 'Spark Plug', 'Jaguar', 'W9j-00', 1147.27);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (25, 'A/C Compressor', 'Ford', 'p2D-39', 1371.79);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (26, 'Battery', 'Ford', 'eu9-96', 2960.23);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (27, 'Air Filter', 'Audi', 'nef-97', 1168.3);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (28, 'Muffler', 'Cadillac', 'Q1c-98', 2438.88);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (29, 'Axle', 'Subaru', 'AHF-37', 376.53);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (30, 'Catalytic Converter', 'Honda', 'Jyb-63', 2333.61);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (31, 'Transmission', 'Dodge', '6rR-50', 1130.84);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (32, 'Fuel Injector', 'Ferrari', 'sqx-24', 1966.2);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (33, 'Muffler', 'Mazda', 'cVc-37', 738.43);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (34, 'Muffler', 'Subaru', 'O8V-82', 2938.3);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (35, 'Piston', 'Nissan', 'WQc-92', 2308.4);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (36, 'Spark Plug', 'Suzuki', 'kYP-90', 1838.93);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (37, 'Clutch', 'Chevrolet', 'ydC-53', 1648.0);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (38, 'Axle', 'GMC', 'Og6-11', 794.39);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (39, 'Alternator', 'Porsche', 'aig-71', 1494.17);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (40, 'Catalytic Converter', 'Chevrolet', 'S0S-01', 2860.19);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (41, 'Battery', 'Chevrolet', 'Ku1-13', 2421.09);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (42, 'Brakes', 'Porsche', 'Jix-23', 2838.24);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (43, 'Transmission', 'Oldsmobile', 'g5u-28', 1393.8);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (44, 'Air Filter', 'Volkswagen', 'BAl-39', 1459.46);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (45, 'Engine Fan', 'Mercedes-Benz', 'oFQ-85', 2902.86);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (46, 'Engine Fan', 'Toyota', '8Qu-63', 2784.24);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (47, 'Catalytic Converter', 'Ford', 'RxY-93', 2342.86);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (48, 'Fuel Injector', 'Dodge', '569-52', 2040.95);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (49, 'Air Filter', 'Volkswagen', 'BjU-10', 2284.88);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (50, 'Catalytic Converter', 'Saab', 'e8y-67', 770.69);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (51, 'Engine Fan', 'Land Rover', 'tHg-89', 2215.15);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (52, 'A/C Compressor', 'Isuzu', 'WSq-34', 209.44);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (53, 'Muffler', 'Mitsubishi', 'BWE-11', 1597.93);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (54, 'Transmission', 'Ford', 'dAr-94', 2916.97);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (55, 'Alternator', 'Ford', '6km-19', 1602.28);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (56, 'Radiator', 'Austin', '1dD-46', 979.48);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (57, 'Clutch', 'Chevrolet', 'CGY-44', 833.58);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (58, 'Spark Plug', 'Scion', 'DEm-68', 2203.77);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (59, 'Muffler', 'Mazda', 'kR1-44', 2599.19);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (60, 'Alternator', 'Buick', 'czH-95', 2530.16);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (61, 'Transmission', 'GMC', 's2Z-77', 434.12);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (62, 'Fuel Injector', 'Subaru', 'RxH-59', 133.47);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (63, 'Engine Fan', 'Mercury', 'iWc-11', 2429.84);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (64, 'Radiator', 'Bentley', 'aXx-61', 1697.86);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (65, 'Muffler', 'Chevrolet', 'tsD-89', 1414.92);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (66, 'Clutch', 'Mazda', 'B3T-49', 2968.12);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (67, 'Transmission', 'GMC', 'oXK-22', 2374.32);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (68, 'Engine Fan', 'Porsche', 'eCc-39', 1698.38);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (69, 'Engine Fan', 'Aston Martin', '4xv-23', 2771.24);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (70, 'Radiator', 'Toyota', 'ZjB-02', 2527.39);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (71, 'Engine Fan', 'Renault', 'plj-93', 2598.59);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (72, 'Engine Fan', 'Toyota', 'dN0-58', 621.62);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (73, 'Clutch', 'GMC', '3a2-39', 606.81);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (74, 'Axle', 'Ford', '03M-57', 1576.63);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (75, 'Fuel Injector', 'Ford', '4wy-88', 2829.34);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (76, 'Fuel Injector', 'Suzuki', 'hec-86', 1136.06);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (77, 'Fuel Injector', 'Cadillac', 'bGG-68', 1735.19);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (78, 'Catalytic Converter', 'Acura', 'kwE-36', 1361.14);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (79, 'A/C Compressor', 'Volkswagen', 'ApZ-33', 1629.41);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (80, 'Radiator', 'Chevrolet', '27F-22', 1469.79);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (81, 'Fuel Injector', 'Dodge', 'iGG-93', 2180.99);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (82, 'Transmission', 'Pontiac', 'YzL-89', 1690.85);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (83, 'Muffler', 'Lexus', 'd5N-63', 264.25);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (84, 'Alternator', 'Buick', '0nA-92', 1363.67);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (85, 'Radiator', 'Chevrolet', '4DV-43', 1511.59);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (86, 'Battery', 'Mercury', '9BJ-71', 1671.73);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (87, 'Air Filter', 'Toyota', 'xdq-03', 355.32);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (88, 'Fuel Injector', 'Aston Martin', 'DL3-64', 1743.87);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (89, 'Muffler', 'Land Rover', '7nv-99', 2422.87);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (90, 'Alternator', 'GMC', 'trU-27', 2626.22);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (91, 'Brakes', 'Ford', 'NX2-96', 1630.92);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (92, 'Muffler', 'Dodge', 'BRt-22', 2449.69);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (93, 'Muffler', 'Ford', 'z5t-40', 1632.69);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (94, 'Spark Plug', 'Lincoln', 'bIn-89', 2048.03);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (95, 'Transmission', 'Plymouth', 'NKx-76', 1415.5);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (96, 'Radiator', 'Ford', 'Kl8-26', 2027.93);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (97, 'Clutch', 'Austin', 'egT-20', 2319.91);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (98, 'Alternator', 'Saturn', 'NCU-43', 1134.5);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (99, 'Brakes', 'Chevrolet', '0vs-83', 1780.28);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (100, 'Fuel Injector', 'Toyota', 'pRi-76', 2943.46);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (101, 'Fuel Injector', 'Ford', 'UQd-61', 737.44);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (102, 'Engine Fan', 'Acura', 'pIU-66', 177.84);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (103, 'Piston', 'Pontiac', 'JoZ-75', 2822.18);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (104, 'Transmission', 'Dodge', 'DJt-72', 1560.12);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (105, 'Radiator', 'Audi', 'msg-28', 1142.09);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (106, 'Transmission', 'BMW', 'S1R-10', 2118.61);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (107, 'Shock Absorbers', 'Ford', 'azM-53', 786.15);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (108, 'Engine Fan', 'Infiniti', 'uCu-54', 2875.61);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (109, 'Battery', 'Hyundai', 'NUw-59', 1746.84);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (110, 'Brakes', 'Pontiac', '7dL-41', 2294.51);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (111, 'Muffler', 'Porsche', 'Yyo-52', 1673.59);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (112, 'Air Filter', 'Ford', 'fah-44', 1602.37);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (113, 'Air Filter', 'Oldsmobile', 'OYx-61', 1970.65);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (114, 'Transmission', 'Chevrolet', 'MJ2-73', 337.3);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (115, 'Radiator', 'Saab', 'Dsn-70', 921.7);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (116, 'Clutch', 'Saab', 'yOn-78', 387.28);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (117, 'A/C Compressor', 'Audi', 'MbJ-76', 2970.82);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (118, 'Spark Plug', 'BMW', 'pSF-55', 141.44);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (119, 'Catalytic Converter', 'Chevrolet', '23U-22', 1493.48);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (120, 'Brakes', 'Mercury', 'pbJ-66', 2081.3);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (121, 'Clutch', 'Honda', 'ngi-83', 1338.77);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (122, 'Shock Absorbers', 'Chevrolet', 'CiA-68', 2509.11);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (123, 'Axle', 'Volvo', 'NCJ-60', 1003.83);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (124, 'Fuel Injector', 'Mercury', 'XnO-86', 1054.21);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (125, 'Battery', 'Cadillac', 'vgM-13', 1046.09);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (126, 'Spark Plug', 'Ford', 'Wvy-97', 272.09);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (127, 'Shock Absorbers', 'Chevrolet', 'Fw3-20', 1795.54);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (128, 'Brakes', 'Aston Martin', 'ns9-86', 2419.88);
insert into Pecas (idPecas, Auto_parts, Brand, Model, Price) values (129, 'Muffler', 'Lotus', '1Cb-57', 2006.83);
